#Traefik router https://doc.traefik.io/traefik/routing/routers/
http:
  routers:
    traefik:
      rule: "Host(`pixel.docker.localhost`)"
      service: "api@internal"
      tls:
        domains:
          - main: "docker.localhost"
            sans:
              - "*.docker.localhost"       

#Traefik TLS https://doc.traefik.io/traefik/https/tls/
tls:
  certificates:
    - certFile: "/etc/certs/pixel-cert.pem"
      keyFile: "/etc/certs/pixel-key.pem"