name: Identity build and test with docker image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
     - 'src/**'
  pull_request:
    branches: [ main ]
    paths:
     - 'src/**'

jobs:

  build-docker-image:
    uses: ./.github/workflows/identity-build-docker-image.yaml
  
  test-with-postgres-db:
    needs: build-docker-image
    uses: ./.github/workflows/identity-test-docker-image-with-postgres.yaml           

  test-with-mongo-db:
   needs: build-docker-image
   uses: ./.github/workflows/identity-test-docker-image-with-mongo.yaml    
